<!DOCTYPE menu [
        <!ELEMENT menu (desayunos)*>
        <!ELEMENT desayunos (desayuno)*>
        <!ELEMENT desayuno (Nombre|PrecioEuros|Descripcion|Calorias)*>
        <!ELEMENT Nombre (#PCDATA)>
        <!ELEMENT PrecioEuros (#PCDATA)>
        <!ELEMENT Descripcion (#PCDATA)>
        <!ELEMENT Calorias (#PCDATA)>
        ]>
<menu>
    <desayunos>
        <desayuno>
            <Nombre>Gofres Belgas</Nombre>
            <PrecioEuros>5.95</PrecioEuros>
            <Descripcion>Dos de nuestros famosos Gofres belgas con abundante sirope</Descripcion>
            <Calorias>650</Calorias>
        </desayuno>
        <desayuno>
            <Nombre>Gofres Belgas con fresas</Nombre>
            <PrecioEuros>7.95</PrecioEuros>
            <Descripcion>Ligeros gofres belgas cubiertos de fresas y nata montada</Descripcion>
            <Calorias>900</Calorias>
        </desayuno>
        <desayuno>
            <Nombre>Gofres Belgas con frutas del bosque</Nombre>
            <PrecioEuros>8.95</PrecioEuros>
            <Descripcion>Ligeros gofres belgas cubiertos con frutas del bosque y nata montada</Descripcion>
            <Calorias>900</Calorias>
        </desayuno>
        <desayuno>
            <Nombre>Tostada Francesa</Nombre>
            <PrecioEuros>4.50</PrecioEuros>
            <Descripcion>Dos gruesas rebanadas de nuestro pan franc√©s casero</Descripcion>
            <Calorias>600</Calorias>
        </desayuno>
        <desayuno>
            <Nombre>Desayuno de la casa</Nombre>
            <PrecioEuros>6.95</PrecioEuros>
            <Descripcion>Dos huevos, bacon o salchicha, tostada y patatas fritas</Descripcion>
            <Calorias>950</Calorias>
        </desayuno>
    </desayunos>
</menu>