<?xml version="1.0"?>
<!DOCTYPE libros [
        <!ELEMENT libros (libro|titulo|autor|descripcion)*>
        <!ELEMENT libro (#PCDATA)>
        <!ELEMENT titulo (#PCDATA)>
        <!ELEMENT autor (#PCDATA)>
        <!ELEMENT descripcion (#PCDATA)>
        ]>
<libros>
    <libro> id="quijote" </libro>
        <titulo>El Quijote</titulo>
        <autor> nombre=cervantes</autor>
        <descripcion>Es el mejor libro de cervantes.  </descripcion>
</libros>